RemovePackage manjaro-settings-manager-notifier
RemovePackage xfwm4
RemovePackage galculator
RemovePackage xfce4-whiskermenu-plugin
RemovePackage snapd
RemovePackage snapd-glib
RemovePackage libpamac-snap-plugin
RemovePackage xf86-video-ati
RemovePackage xf86-video-intel
RemovePackage xfburn
RemovePackage xorg-twm
RemovePackage wallpapers-2018
RemovePackage nano
RemovePackage nano-syntax-highlighting
RemovePackage xcursor-simpleandsoft
RemovePackage manjaro-browser-settings
RemovePackage manjaro-hello
RemovePackage manjaro-wallpapers-18.0

IgnorePackage xfce4-appfinder
IgnorePackage xfce4-battery-plugin
IgnorePackage xfce4-clipman-plugin
IgnorePackage xfce4-cpufreq-plugin
IgnorePackage xfce4-cpugraph-plugin
IgnorePackage xfce4-dict
IgnorePackage xfce4-diskperf-plugin
IgnorePackage xfce4-fsguard-plugin
IgnorePackage xfce4-genmon-plugin
IgnorePackage xfce4-mailwatch-plugin
IgnorePackage xfce4-mount-plugin
IgnorePackage xfce4-mpc-plugin
IgnorePackage xfce4-netload-plugin
IgnorePackage xfce4-notes-plugin
IgnorePackage xfce4-notifyd
IgnorePackage xfce4-panel
IgnorePackage xfce4-power-manager
IgnorePackage xfce4-pulseaudio-plugin
IgnorePackage xfce4-screensaver
IgnorePackage xfce4-screenshooter
IgnorePackage xfce4-sensors-plugin
IgnorePackage xfce4-session
IgnorePackage xfce4-settings
IgnorePackage xfce4-smartbookmark-plugin
IgnorePackage xfce4-systemload-plugin
IgnorePackage xfce4-taskmanager
IgnorePackage xfce4-terminal
IgnorePackage xfce4-time-out-plugin
IgnorePackage xfce4-timer-plugin
IgnorePackage xfce4-verve-plugin
IgnorePackage xfce4-wavelan-plugin
IgnorePackage xfce4-weather-plugin
IgnorePackage xfce4-whiskermenu-plugin
IgnorePackage xfce4-xkb-plugin
IgnorePackage xfconf
IgnorePackage xfdesktop
IgnorePackage networkmanager-vpnc
IgnorePackage yelp

IgnorePackage mugshot
IgnorePackage samba
IgnorePackage xf86-input-elographics
IgnorePackage xf86-input-evdev
IgnorePackage xf86-input-libinput
IgnorePackage xf86-input-void
IgnorePackage xf86-video-intel
IgnorePackage xf86-video-amdgpu
IgnorePackage xf86-video-nouveau
IgnorePackage xdg-desktop-portal-gtk
IgnorePackage xdg-user-dirs
IgnorePackage xdg-utils
IgnorePackage xfsprogs
IgnorePackage xiccd
IgnorePackage xorg-mkfontscale
IgnorePackage xorg-server
IgnorePackage xorg-xinit
IgnorePackage manjaro-application-utility
IgnorePackage timeshift
IgnorePackage timeshift-autosnap-manjaro
IgnorePackage viewnior
IgnorePackage vulkan-intel 
IgnorePackage vulkan-nouveau
IgnorePackage vulkan-radeon
IgnorePackage manjaro-alsa
IgnorePackage thunar
IgnorePackage thunar-archive-plugin
IgnorePackage thunar-media-tags-plugin
IgnorePackage thunar-volman
IgnorePackage tumbler
IgnorePackage ttf-dejavu
IgnorePackage ttf-indic-otf
IgnorePackage ttf-liberation
IgnorePackage update-grub
IgnorePackage wireless-regdb
IgnorePackage wpa_supplicant
IgnorePackage usb_modeswitch
IgnorePackage udev-usb-sync
IgnorePackage udisks2
IgnorePackage texinfo
IgnorePackage which
IgnorePackage wget

RemovePackage networkmanager-openconnect
RemovePackage networkmanager-openvpn
RemovePackage networkmanager-vpn-plugin-openvpn
RemovePackage networkmanager-vpnc
RemovePackage xcursor-vanilla-dmz-aa
RemovePackage wallpapers-juhraya
RemovePackage manjaro-wallpapers-18.0
IgnorePackage manjaro-gstreamer
IgnorePackage xorg-xkill

IgnorePackage manjaro-modem
IgnorePackage manjaro-pipewire
IgnorePackage manjaro-printer
IgnorePackage manjaro-release
IgnorePackage manjaro-settings-manager
IgnorePackage manjaro-system 
IgnorePackage manjaro-xfce-settings
IgnorePackage manjaro-zsh-config
IgnorePackage matcha-gtk-theme
IgnorePackage nfs-utils
IgnorePackage evince
IgnorePackage noto-fonts
IgnorePackage terminus-font
IgnorePackage nss-mdns
IgnorePackage ntfs-3g
IgnorePackage ntp
IgnorePackage numlockx
IgnorePackage os-prober
IgnorePackage pamac-gtk3
IgnorePackage perl
IgnorePackage perl-file-mimeinfo
IgnorePackage plotutils
IgnorePackage poppler-data
IgnorePackage poppler-glib
IgnorePackage plymouth
IgnorePackage plymouth-theme-manjaro
IgnorePackage powertop
IgnorePackage s-nail
IgnorePackage screenfetch
IgnorePackage sof-firmware
IgnorePackage sudo
IgnorePackage sysfsutils
IgnorePackage plocate
IgnorePackage sbctl
IgnorePackage lightdm
IgnorePackage lightdm-gtk-greeter
IgnorePackage lightdm-gtk-greeter-settings
IgnorePackage linux-firmware-meta
IgnorePackage linux618
IgnorePackage linux618-nvidia-open
IgnorePackage logrotate
IgnorePackage lvm2
IgnorePackage mdadm
IgnorePackage man-db
IgnorePackage man-pages
IgnorePackage memtest86+
IgnorePackage memtest86+-efi
IgnorePackage menulibre
IgnorePackage mousepad
IgnorePackage mesa-utils
IgnorePackage mhwd
IgnorePackage mhwd-db
IgnorePackage mkinitcpio-openswap
IgnorePackage modemmanager
IgnorePackage network-manager-applet
IgnorePackage networkmanager
IgnorePackage libpamac-flatpak-plugin
IgnorePackage libgsf
IgnorePackage libopenraw
IgnorePackage libva-intel-driver
IgnorePackage libxnvctrl
IgnorePackage mtpfs
IgnorePackage gvfs
IgnorePackage gvfs-afc
IgnorePackage gvfs-gphoto2
IgnorePackage gvfs-mtp
IgnorePackage gvfs-nfs
IgnorePackage gvfs-smb
IgnorePackage gufw
IgnorePackage inetutils
IgnorePackage inxi
IgnorePackage jfsutils
IgnorePackage install-grub
IgnorePackage lib32-mesa
IgnorePackage lib32-mesa-utils
IgnorePackage lib32-vulkan-nouveau
IgnorePackage lib32-vulkan-radeon
IgnorePackage freetype2
IgnorePackage garcon
IgnorePackage glibc-locales
IgnorePackage gnome-themes-extra
IgnorePackage grub
IgnorePackage grub-btrfs
IgnorePackage grub-theme-manjaro
IgnorePackage diffutils
IgnorePackage dmidecode
IgnorePackage dmraid
IgnorePackage dnsmasq
IgnorePackage dosfstools
IgnorePackage e2fsprogs
IgnorePackage exfatprogs
IgnorePackage f2fs-tools
IgnorePackage efibootmgr
IgnorePackage engrampa
IgnorePackage eog
IgnorePackage exo
IgnorePackage ffmpegthumbnailer
IgnorePackage accountsservice
IgnorePackage acpi
IgnorePackage acpid
IgnorePackage adobe-source-sans-fonts
IgnorePackage alsa-firmware
IgnorePackage alsa-utils
IgnorePackage android-udev
IgnorePackage apparmor
IgnorePackage avahi
IgnorePackage b43-fwcutter
IgnorePackage base
IgnorePackage bash-completion
IgnorePackage btrfs-progs
IgnorePackage cryptsetup
IgnorePackage device-mapper
IgnorePackage catfish
IgnorePackage cpupower
IgnorePackage cronie
